dariuscruceru21/CarSharingFInal

- Models/User.cpp
- Models/User.h
> Models+user

- Models/Employee.cpp
- Models/Employee.h
Employee Class--Getters--Setters
> Employee Class, Getters, Setters

- Models/Admin.cpp
- Models/Admin.h
- Models/Employee.cpp
- Models/Employee.h
Admin class, getters, setters + made Employee attributes proteced
> Admin class

- Models/Order.cpp
- Models/Order.h
Attributes to class Models/Order were added
> attributes added

- Models/Order.cpp
- Models/Order.h
show orders in a specific time interval, search an order by its order number, show the total sum of a time interval. (B4 also copy pasted from discontinued project; made by Philipp Gyarmati)
> Added B4: 

- Models/Order.cpp
- Models/Order.h
Validations (check if the car is used when creating an order, check if the begin time is valid (not greater than end time), check that user does not exceed the number of reservations (5) he can have); automated assigning the order numbers)
> Added B5: 

- Models/Car.cpp
- Models/Car.h
> Declarat clasa Car + gettere si settere

- Models/Order.cpp
- Models/Order.h
verificare daca .cpp e in concordanta cu .h
> some changes to function parameters

- Models/Order.h
- Repository/OrderRepository.cpp
- Repository/OrderRepository.h
> created Order Repo file

- Models/Employee.cpp
- Models/Employee.h
- Repository/EmployeeRepository.cpp
Added conversion functions for CSV Employee.
> Added conversion functions for Employee.

- Models/Order.cpp
- Repositories/OrderRepository.cpp
- Repositories/OrderRepository.h
> Added repository functions (save, delete, update, listAll, searchOrder) + updated fromCSV

- Models/Car.cpp
- Models/Car.h
- Repository/CarRepository.cpp
- Repository/CarRepository.h
Model --> Car ---> CSV Conversion
CarRepository --->  CarRepository.h and first four methods 
*I added the add() method, it wasn't defined in the UML---> CarRepo, idk if it's ok tho
> CarModel CSV Conversion+CarRepository

- Repository/EmployeeRepository.cpp
- Repository/EmployeeRepository.h
mai trebuie logica de CSV implementata
> am facut functiile de update save si delete

- Repository/CarRepository.cpp
- Repository/CarRepository.h
Car Repository: findByLicensePlate, saveCar, and deleteCar methods
> Car Repository: findByLicensePlate, saveCar, and deleteCar methods

- Models/Order.h
- Repository/OrderRepository.cpp
- Repository/OrderRepository.h
Added functions and minor improvements
> Gran b.3 car ordering

- Models/Customer.cpp
- Models/Customer.h
- Models/Employee.cpp
- Models/Order.h
- Models/User.h
Added fromCsv and toCsv conversions for Customer
> Added fromCsv and toCsv conversions for Customer

- Models/Employee.cpp
- Models/Employee.h
- Repository/CustomerHandlingRepository.h
> Changed type of birthdate in employee class

- Models/Customer.cpp
- Models/Customer.h
- Repository/CustomerHandlingRepository.cpp
added empty constructor for customer class
>  new constructor for customer

- Repository/CarRepository.cpp
- Repository/CarRepository.h
> finished car Repository

- Models/Employee.cpp
- Models/Employee.h
voiam sa ma pun sa o fac, da am realizat ca n am cum =))
updateProfile()---> //an Employee should only be able to update his--> remarks and password
> EmployeeMethod

- Controller/OrderController.cpp
- Controller/OrderController.h
Started working on Order Controller
> Order Controller header done

- Controller/CustomerController.cpp
- Controller/CustomerController.h
- Controller/UserController.cpp
- Controller/UserController.h
- Repository/UserRepository.cpp
> Added User COntroller

- Controller/OrderController.cpp
- Controller/OrderController.h
- Models/Order.cpp
- Models/Order.h
- Repository/OrderRepository.cpp
- Repository/OrderRepository.h
changes to Order and OrderRepo class added and some controller functions implemented
> Changes and new funcs implemented

- Models/Order.cpp
Corrected Csv conversions in Order
> Corrected Csv conversions in Order

- Controller/OrderController.cpp
- Controller/OrderController.h
- Repository/OrderRepository.cpp
- Repository/OrderRepository.h
changes to OrderRepo class added and more controller functions implemented
> Chca order controller

- Repository/CustomerHandlingRepository.cpp
> CustomerRepo

- Controller/OrderController.cpp
- Controller/OrderController.h
- Ui/OrderUi.cpp
functions for assigning employee made better
> changed some orderController functions to be more accesible for Ui

- Controller/OrderController.cpp
- Controller/OrderController.h
- Models/Order.cpp
- Models/Order.h
- Ui/OrderUi.cpp
changed Order Functions in UI and Controller
> Chca order controller edits

- Models/Order.cpp
- Models/Order.h
changed Order Functions in UI and Controller
> small changes

- Controller/OrderController.cpp
- Controller/OrderController.h
- Models/Order.cpp
- Models/Order.h
- Repository/OrderRepository.cpp
- Repository/OrderRepository.h
changed time format to string (from tm), changed a few other things (other list to vector conversions etc)
> Multiple changes (not finished):
